interface Props {
  isDark: boolean;
}

const LAST_UPDATED = 'January 1, 2026';

export default function TermsOfUse({ isDark }: Props) {
  const prose = isDark ? 'text-slate-300' : 'text-slate-600';
  const heading = isDark ? 'text-white' : 'text-slate-900';
  const subheading = isDark ? 'text-slate-100' : 'text-slate-800';
  const card = isDark
    ? 'bg-slate-900 border border-white/8'
    : 'bg-white border border-slate-200 shadow-sm';

  const sections = [
    {
      title: '1. Acceptance of Terms',
      content: `By installing or using the ReplyChief Chrome extension or visiting replychief.com, you agree to be bound by these Terms of Use. If you do not agree, please do not use ReplyChief.

These Terms constitute a legally binding agreement between you and Inoviqa ("we", "our", "us"), the company behind ReplyChief.`,
    },
    {
      title: '2. Description of Service',
      content: `ReplyChief is an AI-powered LinkedIn comment generation Chrome extension. It is available on the Chrome Web Store (chrome.google.com/webstore) and helps professionals generate contextually relevant, professional comments for LinkedIn posts.

ReplyChief is a writing assistance tool only. It does not automate, bot, or perform unsanctioned automated actions on LinkedIn or any other platform.`,
    },
    {
      title: '3. Eligibility',
      content: `You must be at least 16 years of age to use ReplyChief. By using the service, you represent that you meet this requirement. If you are using ReplyChief on behalf of an organization, you represent that you have the authority to bind that organization to these Terms.`,
    },
    {
      title: '4. Permitted Use',
      content: `You may use ReplyChief solely for lawful purposes and in accordance with these Terms. Permitted uses include:

• Generating AI-assisted comment suggestions for your personal or professional LinkedIn activity
• Using ReplyChief for your employer's or client's LinkedIn engagement (with proper authorization)
• Creating and managing voice profiles for yourself or clients under your management`,
    },
    {
      title: '5. Prohibited Use',
      content: `You may not use ReplyChief to:

• Violate LinkedIn's Terms of Service or Community Guidelines
• Generate spam, misleading, defamatory, or harmful content
• Attempt to reverse-engineer, decompile, or extract the source code of ReplyChief
• Resell, sublicense, or distribute ReplyChief without our written permission
• Use ReplyChief to engage in any form of harassment, fraud, or illegal activity
• Attempt to circumvent usage limits, subscription restrictions, or account controls

Violation of these terms may result in immediate account termination without refund.`,
    },
    {
      title: '6. Account Registration',
      content: `Some features of ReplyChief require account registration. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. Notify us immediately at support@replychief.com if you suspect unauthorized use of your account.

We reserve the right to suspend or terminate accounts that violate these Terms.`,
    },
    {
      title: '7. Subscriptions & Payments',
      content: `ReplyChief offers Free, Pro, and Lifetime subscription tiers. Paid plans are billed as described at the time of purchase.

**Pro Monthly:** Billed each month. Cancel anytime.
**Pro Yearly:** Billed annually at a discounted rate.
**Lifetime:** One-time payment for lifetime access. The Lifetime plan is priced at $149 for the first 100 slots; subsequent purchases are priced at $299.

All payments are processed securely by Stripe. We do not store your payment card details.

**Refund Policy:** All paid plans include a 7-day money-back guarantee. To request a refund, email support@replychief.com within 7 days of purchase. Refunds are processed within 5–10 business days.

Prices are subject to change with reasonable notice. Changes will not affect active Lifetime plans.`,
    },
    {
      title: '8. Intellectual Property',
      content: `All intellectual property rights in ReplyChief — including the software, AI models, interface designs, logos, and brand assets — are owned by Inoviqa and protected by applicable intellectual property laws.

You are granted a limited, non-exclusive, non-transferable license to use ReplyChief for personal or commercial purposes in accordance with your subscription plan. This license does not transfer any ownership rights to you.

Content generated by ReplyChief (AI-suggested comments) becomes yours to use freely once generated.`,
    },
    {
      title: '9. Third-Party Services',
      content: `ReplyChief integrates with third-party services including LinkedIn, Stripe, and AI providers. Your use of these services is governed by their respective terms and policies. We are not responsible for any third-party service's actions, content, or availability.

ReplyChief is not affiliated with, endorsed by, or sponsored by LinkedIn Corporation.`,
    },
    {
      title: '10. LinkedIn Compliance',
      content: `ReplyChief is designed to be used in compliance with LinkedIn's User Agreement (linkedin.com/legal/user-agreement). ReplyChief:

• Never auto-posts comments on your behalf
• Never requires your LinkedIn login credentials
• Never scrapes or bulk-harvests LinkedIn data
• Operates as a passive writing assistant within the LinkedIn interface

You are solely responsible for ensuring your use of LinkedIn complies with LinkedIn's Terms of Service.`,
    },
    {
      title: '11. Disclaimer of Warranties',
      content: `ReplyChief is provided "as is" and "as available" without any warranties of any kind, express or implied. We do not warrant that:

• The service will be uninterrupted or error-free
• AI-generated content will be accurate, appropriate, or effective for your purposes
• The service will meet your specific requirements

You use ReplyChief at your own risk. AI-generated content should always be reviewed before posting.`,
    },
    {
      title: '12. Limitation of Liability',
      content: `To the fullest extent permitted by law, Inoviqa shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of ReplyChief, including but not limited to loss of profits, data, or goodwill.

Our total liability to you for any claims under these Terms shall not exceed the amount you paid for ReplyChief in the 12 months preceding the claim.`,
    },
    {
      title: '13. Governing Law',
      content: `These Terms are governed by the laws of Bangladesh. Any disputes shall be subject to the exclusive jurisdiction of the courts of Dhaka, Bangladesh.

If any provision of these Terms is found unenforceable, the remaining provisions will continue in full effect.`,
    },
    {
      title: '14. Changes to Terms',
      content: `We may update these Terms from time to time. We will notify you of material changes via email or an in-app notice. Continued use of ReplyChief after changes constitutes your acceptance of the updated Terms.`,
    },
    {
      title: '15. Contact',
      content: `For questions about these Terms, contact us:

Email: support@replychief.com
Address: 375/12 Mirpur, Dhaka, Bangladesh
Company: Inoviqa (inoviqa.com)`,
    },
  ];

  return (
    <main className={`pt-28 pb-24 ${isDark ? 'bg-slate-950' : 'bg-slate-50'}`}>
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="text-center mb-14">
          <div
            className={`inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-semibold uppercase tracking-wider mb-4 ${isDark ? 'bg-blue-500/10 border border-blue-500/20 text-blue-400' : 'bg-blue-50 border border-blue-200 text-blue-600'}`}
          >
            Legal
          </div>
          <h1 className={`text-4xl sm:text-5xl font-extrabold tracking-tight mb-4 ${heading}`}>
            Terms of <span className="text-gradient">Use</span>
          </h1>
          <p className={`text-sm ${prose}`}>Last updated: {LAST_UPDATED}</p>
        </div>

        <div className={`rounded-2xl p-8 sm:p-10 space-y-10 ${card}`}>
          {sections.map((section, i) => (
            <div key={i}>
              <h2 className={`text-xl font-bold mb-3 ${subheading}`}>{section.title}</h2>
              <div className={`text-sm leading-relaxed ${prose}`}>
                {section.content.split('\n').map((line, j) => {
                  const parts = line.split(/(\*\*[^*]+\*\*)/g);
                  if (parts.length > 1) {
                    return (
                      <p key={j} className="mb-1.5">
                        {parts.map((part, k) =>
                          part.startsWith('**') && part.endsWith('**') ? (
                            <strong key={k} className={subheading}>
                              {part.replace(/\*\*/g, '')}
                            </strong>
                          ) : (
                            <span key={k}>{part}</span>
                          )
                        )}
                      </p>
                    );
                  }
                  return line ? (
                    <p key={j} className="mb-1.5">
                      {line}
                    </p>
                  ) : (
                    <br key={j} />
                  );
                })}
              </div>
            </div>
          ))}
        </div>

        {/* Back link */}
        <div className="mt-10 text-center">
          <a
            href="/"
            onClick={(e) => {
              e.preventDefault();
              window.history.pushState({}, '', '/');
              window.dispatchEvent(new PopStateEvent('popstate'));
            }}
            className={`inline-flex items-center gap-2 text-sm font-semibold transition-all duration-200 ${isDark ? 'text-blue-400 hover:text-blue-300' : 'text-blue-600 hover:text-blue-700'}`}
          >
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M10.5 19.5 3 12m0 0 7.5-7.5M3 12h18" />
            </svg>
            Back to Home
          </a>
        </div>
      </div>
    </main>
  );
}
